substitutions:
  platform: esp32
  board: nodemcu-32s
  uart_tx_pin: "25"
  uart_rx_pin: "26"

esphome:
  name: flexispot
  platform: $platform
  board: $board

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: desk_uart
  baud_rate: 9600
  tx_pin: $uart_tx_pin
  rx_pin: $uart_rx_pin
  debug:

logger:
  level: DEBUG

sensor:
  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: 60s

button:
  - platform: uart
    name: "Preset 1"
    id: desk_preset1
    data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Preset 2"
    id: desk_preset2
    data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Stand"
    id: desk_stand
    data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]
    uart_id: desk_uart

  - platform: uart
    name: "Sit"
    id: desk_sit
    data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]
    uart_id: desk_uart

web_server:
  port: 80
  ota: false

mdns:
  services:
    - service: "_flexispot"
      protocol: "_tcp"
      port: 80
