substitutions:
  serial_number: 8caab551c301
  uart_tx_pin: D6
  uart_rx_pin: D5

esphome:
  name: flexispot-$serial_number
  friendly_name: "Flexispot E7"

  # Wake Desk by sending the "M" command
  # This will pull the current height after boot
  on_boot:
    priority: -10
    then:
      - button.press: button_m

external_components:
  - source: components

esp8266:
  board: nodemcuv2

logger:
  level: info

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: desk_uart
  baud_rate: 9600
  tx_pin: $uart_tx_pin
  rx_pin: $uart_rx_pin

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: flexispot
    name: "Desk Height"
    uart_id: desk_uart

switch:
  - platform: uart
    name: "Up"
    id: switch_up
    icon: mdi:arrow-up-bold
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true

  - platform: uart
    name: "Down"
    id: switch_down
    icon: mdi:arrow-down-bold
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    internal: true

  - platform: uart
    name: "Alarm off"
    id: switch_alarm
    icon: mdi:alarm
    data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xac, 0x90, 0x9d]
    uart_id: desk_uart
    send_every: 108ms
    on_turn_on:
      - delay: 3000ms
      - switch.turn_off: switch_alarm
    entity_category: "config"

button:
  - platform: uart
    name: "Preset 1"
    icon: mdi:numeric-1-circle
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]

  - platform: uart
    name: "Preset 2"
    icon: mdi:numeric-2-circle
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]

  - platform: uart
    name: "Stand"
    icon: mdi:human-handsup
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]

  - platform: uart
    name: "Sit"
    icon: mdi:chair-rolling
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x00, 0x01, 0xac, 0x60, 0x9d]

  - platform: uart
    name: "Memory"
    id: button_m
    icon: mdi:alpha-m-box
    entity_category: "config"
    uart_id: desk_uart
    data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]

  - platform: uart
    name: "Alarm"
    id: button_alarm
    icon: mdi:alarm
    data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xac, 0x90, 0x9d]
    uart_id: desk_uart

# web_server:
#   port: 80

# mdns:
#   services:
#     - service: "_flexispot"
#       protocol: "_tcp"
#       port: 80
